<?php

function form_fun_menu() {
  $items = array();
  $items['form_fun/cake'] = array(
    'title' => 'Cake or Pie?',
    'page callback' => 'form_fun_cake_page',
    'access arguments' => array('access content'),
    'file' => 'form_fun.cake.inc',
    'weight' => 1,
  );

  $items['form_fun/tree'] = array(
    'title' => 'Form Using Tree',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_fun_tree'),
    'access arguments' => array('access content'),
    'file' => 'form_fun.tree.inc',
    'weight' => 2,
  );

  $items['form_fun/states'] = array(
    'title' => 'Partners',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_fun_partner'),
    'access arguments' => array('access content'),
    'file' => 'form_fun.partner.inc',
    'weight' => 3,
  );

  return $items;
}
